# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\x12\x0btransaction\"\x9b\x01\n\x0bTransaction\x12\x13\n\x06t_time\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04t_id\x18\x02 \x01(\x03H\x01\x88\x01\x01\x12\x1a\n\rt_customer_id\x18\x03 \x01(\x03H\x02\x88\x01\x01\x12\x15\n\x08t_amount\x18\x04 \x01(\x01H\x03\x88\x01\x01\x42\t\n\x07_t_timeB\x07\n\x05_t_idB\x10\n\x0e_t_customer_idB\x0b\n\t_t_amountb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTION']._serialized_start=35
  _globals['_TRANSACTION']._serialized_end=190
# @@protoc_insertion_point(module_scope)
